/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_startech_picktime_NativeMethod */

#ifndef _Included_tech_startech_picktime_NativeMethod
#define _Included_tech_startech_picktime_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_startech_picktime_NativeMethod
 * Method:    getStringName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tech_startech_picktime_NativeMethod_getStringName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
